name: Test
on: [workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        uses: Git-Louro/hello-world-docker-action@v1
        with:
          who-to-greet: '@octocat'
